// MIT license

// WARNING: This file has automatically been generated on Mon, 06 May 2019 13:18:48 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package Natasha data structures used for CLI
*/
package headers
