// MIT license

// WARNING: This file has automatically been generated on Wed, 15 May 2019 12:37:10 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package Natasha data structures used for CLI
*/
package headers
