// MIT license

// WARNING: This file has automatically been generated on Fri, 10 May 2019 13:27:04 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package Natasha data structures used for CLI
*/
package headers
