// MIT license

// WARNING: This file has automatically been generated on Fri, 10 May 2019 13:27:04 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package headers

/*
#include "/root/natv2/src/cli.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
