// MIT license

// WARNING: This file has automatically been generated on Wed, 15 May 2019 12:37:10 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package headers

/*
#include "/root/natv2/src/cli.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// NatashaAppStats as declared in kaminek/natasha-cli:0
type NatashaAppStats struct {
	DropNoRule             uint64
	DropNatCondition       uint64
	DropBadL3Cksum         uint64
	RxBadL4Cksum           uint64
	DropUnknownIcmp        uint64
	DropUnhandledEthertype uint64
	DropTxNotsent          uint64
}

// NatashaCmdReply as declared in kaminek/natasha-cli:0
type NatashaCmdReply struct {
	Type           byte
	Status         byte
	DataSize       uint16
}

// NatashaEthStats as declared in kaminek/natasha-cli:0
type NatashaEthStats struct {
	Ipackets       uint64
	Opackets       uint64
	Ibytes         uint64
	Obytes         uint64
	Imissed        uint64
	Ierrors        uint64
	Oerrors        uint64
	RxNombuf       uint64
	QIpackets      [16]uint64
	QOpackets      [16]uint64
	QIbytes        [16]uint64
	QObytes        [16]uint64
	QErrors        [16]uint64
}
