// MIT license

// WARNING: This file has automatically been generated on Mon, 06 May 2019 13:18:48 UTC.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package headers

/*
#include "/root/natv2/src/cli.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// NatashaCmdReply as declared in kaminek/natasha-cli:0
type NatashaCmdReply struct {
	Type           byte
	Status         byte
	DataSize       uint16
}

// NatashaEthStats as declared in kaminek/natasha-cli:0
type NatashaEthStats struct {
	Ipackets       uint
	Opackets       uint
	Ibytes         uint
	Obytes         uint
	Imissed        uint
	Ierrors        uint
	Oerrors        uint
	RxNombuf       uint
	QIpackets      [16]uint
	QOpackets      [16]uint
	QIbytes        [16]uint
	QObytes        [16]uint
	QErrors        [16]uint
}
